// <auto-generated />
using System;
using Infrastructure.Adapters.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ModelAggregate.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("Domain.VehicleAddingSaga.VehicleAddingSaga", b =>
                {
                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("SagaId");

                    b.ToTable("vehicle_adding_saga", (string)null);
                });

            modelBuilder.Entity("Domain.VehicleAggregate.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("vehicle_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "addinginprogress"
                        },
                        new
                        {
                            Id = 2,
                            Name = "added"
                        },
                        new
                        {
                            Id = 3,
                            Name = "notadded"
                        },
                        new
                        {
                            Id = 4,
                            Name = "readiedforrelease"
                        },
                        new
                        {
                            Id = 5,
                            Name = "released"
                        },
                        new
                        {
                            Id = 6,
                            Name = "occupied"
                        },
                        new
                        {
                            Id = 7,
                            Name = "serviced"
                        },
                        new
                        {
                            Id = 8,
                            Name = "deleted"
                        });
                });

            modelBuilder.Entity("Domain.VehicleAggregate.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("status_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("status_id");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Adapters.Postgres.Inbox.InboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_inbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_inbox_messages_unprocessed"), new[] { "EventId", "Type" });

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Adapters.Postgres.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "OccurredOnUtc", "ProcessedOnUtc" }, "IX_outbox_messages_unprocessed"), new[] { "EventId", "Type" });

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Domain.ModelAggregate.Model", b =>
                {
                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Brand", "Brand", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("brand");

                            b1.HasKey("ModelId");

                            b1.ToTable("model");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.CarModel", "CarModel", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("car_model");

                            b1.HasKey("ModelId");

                            b1.ToTable("model");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Category", "Category", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<char>("Character")
                                .HasColumnType("character(1)")
                                .HasColumnName("category");

                            b1.HasKey("ModelId");

                            b1.ToTable("model");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Tariff", "Tariff", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("PricePerDay")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("price_per_day");

                            b1.Property<decimal>("PricePerHour")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("price_per_hour");

                            b1.Property<decimal>("PricePerMinute")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("price_per_minute");

                            b1.HasKey("ModelId");

                            b1.ToTable("model");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.Navigation("Brand")
                        .IsRequired();

                    b.Navigation("CarModel")
                        .IsRequired();

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Tariff")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.VehicleAggregate.Vehicle", b =>
                {
                    b.HasOne("Domain.ModelAggregate.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_model_id");

                    b.HasOne("Domain.VehicleAggregate.Status", "Status")
                        .WithMany()
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_status_id");

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("color");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.FuelLevel", "FuelLevel", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Percents")
                                .HasColumnType("integer")
                                .HasColumnName("fuel_level_percents");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.PlateNumber", "PlateNumber", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("plate_number");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("Domain.SharedKernel.ValueObjects.Vin", "Vin", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vin");

                            b1.HasKey("VehicleId");

                            b1.ToTable("vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("FuelLevel")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PlateNumber")
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Vin")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
